### ISSUE TITLE
Is this https://debut-demo.myshopify.com compliant with Online Store 2.0

### ISSUE THREAD

**Issue by BecAndCall** [mmarienko/debut#5]
Hello.

I'm trying to support one of my clients who loves his Debut theme on Shopify. Unfortunately, it no longer works like it used to. I have uploaded the  Debut version 17.14.1 theme I found in a thread and asked him to try that but I don't think it will be supported by Shopify if something happens. Is your debut-demo.myshopify.com a 2.0 version or still a vintage version?

My coding skills are intermediate and I want to direct him to the best overall option for him: replacement theme (Dawn?) or hire a Partner to migrate the code to 2.0. You would think they would offer an obvious Debut replacement option since it was such a popular theme.

Any input would be helpful. Thanks so much, Bec

**Comment by mmarienko** [comment]
Hi, Bec. https://debut-demo.myshopify.com/ is just an example of what Shopify's Debut theme looks like. My code is not used there, it is the old (vintage) version. However, this repository presents you with OS 2.0 which you can download and install for your client. Shopify no longer supports the Debut theme and has no plans to update it to OS 2.0.

The best solution is to migrate the code to version 2.0, as using Dawn is a way to do it from scratch and may take longer.

Please close this issue if my comment solves it.

**Comment by BecAndCall** [comment]
Thank you for the quick reply. Regarding: " OS 2.0 which you can download and install for your client"  How/where would I download the OS 2.0 version?

**Comment by mmarienko** [comment]
<img width="1166" alt="Screenshot 2024-02-07 at 14 27 34" src="https://github.com/mmarienko/debut/assets/64919508/9cfb0bf7-237a-4ee4-bbbf-24618a2a4660">

**Comment by BecAndCall** [comment]
Thank you!
